# Generated by Django 4.0.3 on 2022-05-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
